export const facebookEvent = {
  ViewContent: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "ecommerce.items.item_id" },
    content_type: { type: "string", placeholder: "product" },
    contents: { type: "string", placeholder: "product" },
    value: { type: "string" },
    currency: { type: "string" },
  },
  AddToCart: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "ecommerce.items.item_id" },
    content_type: { type: "string", placeholder: "product" },
    value: { type: "string" },
    currency: { type: "string" },
  },
  AddToWishlist: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "ecommerce.items.item_id" },
    contents: { type: "string", placeholder: "product" },
    value: { type: "string" },
    currency: { type: "string" },
  },
  InitiateCheckout: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "ecommerce.items.item_id" },
    value: { type: "string" },
    currency: { type: "string" },
    num_items: { type: "string" },
  },
  AddPaymentInfo: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "ecommerce.items.item_id" },
    contents: { type: "string", placeholder: "product" },
    value: { type: "string" },
    currency: { type: "string" },
  },
  Purchase: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "ecommerce.items.item_id" },
    content_type: { type: "string", placeholder: "product" },
    quantity: { type: "string", placeholder: "product" },
    value: { type: "string" },
    currency: { type: "string" },
    num_items: { type: "string" },
  },
  Lead: {
    value: { type: "string" },
    currency: { type: "string" },
  },
  CompleteRegistration: {
    value: { type: "string" },
    currency: { type: "string" },
  },
};
