export const facebookEvent = {
  AddPaymentInfo: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "id" },
    value: { type: "string", placeholder: "ecommerce.value" },
    currency: { type: "string", placeholder: "ecommerce.currency" },
  },
  AddToCart: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "id" },
    content_type: { type: "string", placeholder: "product" },
    value: { type: "string", placeholder: "ecommerce.value" },
    currency: { type: "string", placeholder: "ecommerce.currency" },
  },
  AddToWishlist: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "id" },
    value: { type: "string", placeholder: "ecommerce.value" },
    currency: { type: "string", placeholder: "ecommerce.currency" },
  },
  CompleteRegistration: {
    value: { type: "string", placeholder: "ecommerce.value" },
    currency: { type: "string", placeholder: "ecommerce.currency" },
  },
  Contact: {},
  FindLocation: {},
  InitiateCheckout: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "id" },
    value: { type: "string", placeholder: "ecommerce.value" },
    currency: { type: "string", placeholder: "ecommerce.currency" },
  },
  Lead: {
    value: { type: "string", placeholder: "ecommerce.value" },
    currency: { type: "string", placeholder: "ecommerce.currency" },
  },
  Purchase: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "id" },
    content_type: { type: "string", placeholder: "product" },
    quantity: { type: "string", placeholder: "product" },
    value: { type: "string", placeholder: "ecommerce.value" },
    currency: { type: "string", placeholder: "ecommerce.currency" },
  },
  Schedule: {},
  Search: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "id" },
    content_type: { type: "dropdown", placeholder: "product" },
    value: { type: "string", placeholder: "ecommerce.value" },
    currency: { type: "string", placeholder: "ecommerce.currency" },
    search_string: { type: "string", placeholder: "ecommerce.search_string" },
  },
  StartTrial: {
    currency: { type: "string", placeholder: "ecommerce.currency" },
    predicted_ltv: { type: "string", placeholder: "ecommerce.predicted_ltv" },
    value: { type: "string", placeholder: "ecommerce.value" },
  },
  SubmitApplication: {},
  Subscribe: {
    currency: { type: "string", placeholder: "ecommerce.currency" },
    predicted_ltv: { type: "string", placeholder: "ecommerce.predicted_ltv" },
    value: { type: "string", placeholder: "ecommerce.value" },
  },
  ViewContent: {
    productListPath: { type: "string", placeholder: "ecommerce.items" },
    idPath: { type: "string", placeholder: "id" },
    content_type: { type: "dropdown", placeholder: "product" },
    value: { type: "string", placeholder: "ecommerce.value" },
    currency: { type: "string", placeholder: "ecommerce.currency" },
  },
};
